name: "SideBlog"
description: "Le blog de SideProg"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty

safe: true
source: sideprog/sideprog.github.com
destination: blog
lsi: false
pygments: true