name: "SideBlog"
description: "Le blog de SideProg"



paginate: 10

markdown: rdiscount
permalink: pretty

safe: true
source: "sideprog/sideprog.github.com"
destination: "_site"
lsi: false
pygments: true